version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000" # host:container
    volumes:
      - .:/opt/app
      # Hack for excluding node_modules
      - /opt/app/node_modules/
    entrypoint:
      - npm
      - start
